// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4y8L2xUe-4jsy-QjDtaCw84oCHD2sWKY',
    appId: '1:1071469872801:web:b834a5d90d3d68354352e0',
    messagingSenderId: '1071469872801',
    projectId: 'datingapp-96c38',
    authDomain: 'datingapp-96c38.firebaseapp.com',
    storageBucket: 'datingapp-96c38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_ag46nTw_WDHovNxqdZ8uXCEs3rdalg',
    appId: '1:1071469872801:android:22f2b9c86574b96c4352e0',
    messagingSenderId: '1071469872801',
    projectId: 'datingapp-96c38',
    storageBucket: 'datingapp-96c38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdGlRmbSVepFTWlH_b-7pLHdh5ZmAj8Gw',
    appId: '1:1071469872801:ios:8ad8e973e0af7f844352e0',
    messagingSenderId: '1071469872801',
    projectId: 'datingapp-96c38',
    storageBucket: 'datingapp-96c38.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );
}
